### ISSUE TITLE
OcclusionDetector.py line 150~152 can't find Entropy function definition

### ISSUE THREAD

**Issue by hhmy27** [ChenZhouUC/CamOcclusionDetector#1]
In `OcclusionDetector.py` line 150~152，the Entropy function and it's parameter is Unresolved reference
```
    vert_score = Entropy(vert_binning)
    hori_score = Entropy(hori_binning)
    radius_score = Entropy(radius_binning)
```

Are they spelled wrong ? or this repo lack some file ? ...🧐 
Please fix that ， Thank you  👍

**Comment by ChenZhouUC** [comment]
> In `OcclusionDetector.py` line 150~152，the Entropy function and it's parameter is Unresolved reference
> 
> ```
>     vert_score = Entropy(vert_binning)
>     hori_score = Entropy(hori_binning)
>     radius_score = Entropy(radius_binning)
> ```
> 
> Are they spelled wrong ? or this repo lack some file ? ...
> Please fix that ， Thank you

Indeed this is an internal project, and these scripts are only for research purposes. The code you mentioned here is just an operator under developing. The function `FragmentDetector` is not yet used in PROD ENV.

I think you can refer to my ideas but not simply copy it. Maybe you can find a more efficient and simplified traditional detector to solve the camera occlusion problem. My code here will not be maintained frequently since it is online and working properly for now. 

Thanks for your focus. Please keep digging further.
